weather_data:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: united-button-490809-c4
      dataset: global_weather
      threads: 4
      keyfile: /home/liza/projects/global-weather-data/bigquery-key.json
      location: EU        
      timeout_seconds: 300